### ISSUE TITLE
panic: route ip+net: no such network interface

### ISSUE THREAD

**Issue by grayguest** [tengzhangchao/PortScan#1]
```
[root@VM portscan]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.26.15.222  netmask 255.255.255.0  broadcast 10.26.15.255
        ether 52:54:00:04:f7:35  txqueuelen 1000  (Ethernet)
        RX packets 17490753  bytes 3856909094 (3.5 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19965515  bytes 3772895243 (3.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 15421233  bytes 3206991270 (2.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15421233  bytes 3206991270 (2.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@VM portscan]# python3 tcp_syn_scan.py 
panic: route ip+net: no such network interface

goroutine 17 [running, locked to thread]:
main.interfaceAddress(0xc4200142a8, 0x1, 0x7f0e681b2700, 0xc42005e0c0)
        /root/PortScan/python+go/tcp_syn_scan.go:277 +0x11d
main.Scan(0x7f0e6fb0f710, 0x7f0e6fab8ef0, 0x7f0e6fc2b210, 0xc400000008)
        /root/PortScan/python+go/tcp_syn_scan.go:83 +0x1f8
main._cgoexpwrap_82086776782e_Scan(0x7f0e6fb0f710, 0x7f0e6fab8ef0, 0x7f0e6fc2b210, 0x0)
        command-line-arguments/_obj/_cgo_gotypes.go:65 +0x74
Aborted (core dumped)
```
明明有eth0，但是报错提示没有该网卡。
使用得是直接clone下来的文件，
后来自己用go build，也是一样的错误。

**Comment by grayguest** [comment]
发现py3不行。。

**Comment by grayguest** [comment]
result = lib.Scan("117.51.1.11",b"1-65534",b"eth0") # 加b即可

**Comment by tengzhangchao** [comment]
> "

因为py3中的字符编码与py2不一样

**Comment by grayguest** [comment]
> > "
> 
> 因为py3中的字符编码与py2不一样

go中指定网卡名称这一点我感觉不太好，我看go代码中把网卡名称转换成了ip地址（源ip地址），然后发包的时候指定了源ip地址，我对go也没学过，在网上找了一些其他的go扫描代码，发现其实是可以不指定源ip地址的，但是都没有github主你后面的那些代码（自定义发tcp包的代码），我猜测应该是tcp自定义包需要源ip字段的原因？我后来改成了用py获取ip地址直接传给go的方式。

**Comment by grayguest** [comment]
> > "
> 
> 因为py3中的字符编码与py2不一样

另外，github主你有udp的检测代码么？虽然不常用~

**Comment by 13661785021** [comment]
> > ”
> 
> 因为py3中的字符编码与py2不一样

那go中这样的错误原因是什么？
